version: '3.9'
services:
  skinsight-backend-dev:
    container_name: skinsight-backend-dev
    image: ghcr.io/florentkaram/skinsight-backend/skinsight-backend-dev:latest
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.skinsight-backend-dev.entrypoints: websecure
      traefik.http.routers.skinsight-backend-dev.tls: true
      traefik.http.routers.skinsight-backend-dev.rule: (Host(`sample-restaurant.com`) || Host(`www.sample-restaurant.com`)) && PathPrefix(`/dev/backskinsight/`)
    ports:
      - 3003:3000
    networks:
      - skinsight-backend

networks:
  skinsight-backend:
    name: skinsight-backend
