name: skinsight-backend

on :
  push :
    branches: ["dev"]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Publish Docker Image to GitHub Registry
      uses: VaultVulp/gp-docker-action@1.2.0
      with:
        github-token: ${{ secrets.GIT_TOKEN }}
        image-name: skinsight-backend-dev
        dockerfile: Dockerfile-dev
        custom-args: --build-arg=DATABASE_URL=${{secrets.DATABASE_URL}}
  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build
    steps: 
      - name: SSH Execute Commands
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          privateKey: ${{ secrets.SSH_KEY }}
          debug: false
          command: | 
            cd /projects/skinsight/skinsight-backend-dev/
            docker login ghcr.io -u ${{ secrets.GIT_USERNAME }} -p ${{ secrets.GIT_TOKEN }}
            git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/FlorentKaram/skinsight-backend.git
            git pull
            docker stop skinsight-backend-dev
            docker rm skinsight-backend-dev
            docker image rm -f ghcr.io/florentkaram/skinsight-backend/skinsight-backend-dev
            docker compose -f docker-compose-dev.yml up -d 
