name: skinsight-backend

on :
  push :
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    - name: creating env variables
      run: |
        touch .env
        echo DATABASE_URL=${{secrets.DATABASE_URL}} >> .env
        echo NODE_ENV="prod" >> .env
        cat .env
        ls -la
    - name: Publish Docker Image to GitHub Registry
      uses: VaultVulp/gp-docker-action@1.2.0
      with:
        github-token: ${{ secrets.GIT_TOKEN }}
        image-name: skinsight-backend
        custom-args: --build-arg=DATABASE_URL=${{secrets.DATABASE_URL}}


  Analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Analyze with SonarQube
        
      # You can pin the exact commit or the version.
      # uses: SonarSource/sonarqube-scan-action@v1.1.0
      uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on SonarQube, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # add the URL of your instance to the secrets of this repo with the name SONAR_HOST_URL (Settings > Secrets > Actions > add new repository secret)
  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build
      - Analysis

    steps: 
      - name: SSH Execute Commands
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          privateKey: ${{ secrets.SSH_KEY }}
          debug: false
          command: | 
            cd /projects/skinsight/skinsight-backend/
            docker login ghcr.io -u ${{ secrets.GIT_USERNAME }} -p ${{ secrets.GIT_TOKEN }}
            git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/FlorentKaram/skinsight-backend.git
            git pull
            docker stop skinsight-backend
            docker rm skinsight-backend
            docker image rm -f ghcr.io/florentkaram/skinsight-backend/skinsight-backend
            docker compose up -d
